### ISSUE TITLE
Bucketing and AWS Lambda

### ISSUE THREAD

**Issue by chhatch** [abtasty/flagship-js-sdk#70]
Are there any know issues with using this sdk in bucketing mode in am AWS Lambda deployment? We're intermittently getting errors that come in pairs:
```
AbortError: The user aborted a request.
```
and
```
Method fetchFlags is deactivated while SDK status is: NOT_INITIALIZED
```
We have not been able to reproduce this error locally. Any help will be greatly appreciated.

**Comment by David-Flagship** [comment]
Hello @chhatch, thanks for the warn, we'll check this one and update this issue when we have news to provide. 

Have a great day

**Comment by chhatch** [comment]
I forgot to include our config. It's pretty minimal:
```js
{
    decisionMode: DecisionMode.BUCKETING,
    logLevel: LogLevel.DEBUG,
    pollingInterval: 120,
}
```

**Comment by Heihokon** [comment]
Hello @chhatch

`AbortError: The user aborted a request.`

The first one often occurs when a request has timed out. Default request timeout is 2s 

`Method fetchFlags is deactivated while SDK status is: NOT_INITIALIZED`

This one happens when fetchFlags method is called but the SDK is not yet initialized, initialization fails when EnvId and apiKey are empty or in bucketing mode when the first request of bucketing file fails

This comes in pairs as the first request of bucketing file throws a timeout error and sets the SDK status to **NOT_INITIALIZED**.  Normally, the next iteration if successful will set statut to **READY**

You can reproduce this locally if you degrade your internet quality.

_Request timeout can be increased through `timeout` property of config_

Hope this will help you, thank you.

**Comment by chhatch** [comment]
Thanks so much for getting back to me.

> `Method fetchFlags is deactivated while SDK status is: NOT_INITIALIZED`
> 
> This one happens when fetchFlags method is called but the SDK is not yet initialized, initialization fails when EnvId and apiKey are empty or in bucketing mode when the first request of bucketing file fails

Would a polling failure cause the SDK to revert to an unitialized state? Our code is actually set up to wait for the first bucketing success before calling `fsVisitor.fetchFlags()`.

**Comment by Heihokon** [comment]
> Would a polling failure cause the SDK to revert to an unitialized state?

In bucketing mode When the SDK starts, the status is `STARTING`, only for the first polling request the status becomes `POLLING` then if this first request succeeds the status changes to `READY` otherwise if the first request failed the status changes to `NOT_INITIALIZED`

> Our code is actually set up to wait for the first bucketing success before calling fsVisitor.fetchFlags()

How do you know the first bucketing is a success?

It's important to note that in JS, if the `fetchNow` property is true (the default is true), a `fetchFlags` is automatically called even if you haven't called it explicitly

**Comment by chhatch** [comment]
We don't know that the first bucketing is is a success. We wait for the first bucketing **_success_** which is not necessarily the first attempt to get the data.

> It's important to note that in JS, if the fetchNow property is true (the default is true), a fetchFlags is automatically called even if you haven't called it explicitly

I think you're on to something there, but I just want to make sure that I understand you. Is this right?
```js
const config = {
    decisionMode: DecisionMode.BUCKETING,
    fetchNow: true  // defaults to true
    }

Flagship.start(FLAGSHIP_ID, FLAGSHIP_API_KEY, config);

const fsVisitor = Flagship.newVisitor({ // fetchFlags is implicitly called here?
    visitorId,
    context,
  })
const flags = await fsVisitor.fetchFlags()
```

**Comment by Heihokon** [comment]
```javascript
const config = {
    decisionMode: DecisionMode.BUCKETING,
    fetchNow: true  // defaults to true
    }

Flagship.start(FLAGSHIP_ID, FLAGSHIP_API_KEY, config);

const fsVisitor = Flagship.newVisitor({ // fetchFlags is implicitly called here?
    visitorId,
    context,
  })
const flags = await fsVisitor.fetchFlags()
```
Yes, it is right.

Be careful to use `fetchNow:true` in bucketing mode if your code is linear like this, maybe the first bucketing file request is still running when fetchFlags is called.

To find the status of the first bucketing file request : 
- You can check the SDK status. [doc](https://docs.developers.flagship.io/docs/js-v3#getstatus-function)
- There are also these 2 callbacks in config : [onBucketingSuccess](https://docs.developers.flagship.io/docs/js-v3#onbucketingsuccess) and [onBucketingFail](https://docs.developers.flagship.io/docs/js-v3#onbucketingfail)

**Comment by David-Flagship** [comment]
Hello @chhatch, i come to take some news, does the issue is still here for you ?

Thanks and have a nice day !

**Comment by chhatch** [comment]
Thanks for checking in. We did not resolve our issues. Bucketing mode did not seem to be working properly, so we switched to using the decision api instead.

**Comment by David-Flagship** [comment]
Oh well, sorry to hear that, i will ask to my team to check if this issue can be resolved on our side, thanks for the feedback and hope you enjoy using Flagship
